version: "3.2"
services:
  apache:
    build: './Apache/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./Apache/www/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=testroot
  tomcat:
    image: tomcat:9.0.31-jdk8-openjdk
networks:
  frontend:
  backend: