---
- name: Apache
  hosts: localhost
  become: yes
  roles:
    - apache

- name: MySQL
  hosts: localhost
  become: yes
  roles:
    - mysql

- name: Java 8
  hosts: localhost
  become: yes
  roles:
    - java

- name: Tomcat deployment playbook
  hosts: localhost          # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  vars:
    tomcat_ver: 9.0.31                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  roles:
    - tomcat